#!/usr/bin/env ansible-playbook
---

- hosts: stunnel4_servers
  gather_facts: False
  tags: servers

  vars_files: &stunnel4
    - vars/ext/stunnel4s.yml
    - vars/ext/stunnel4vm.yml

  tasks:

    - apt: name=stunnel4 state=present
    - set_fact: { stunnel4_clients: [] }
    - set_fact:
        stunnel4_clients: '{{ stunnel4vm_name[inventory_hostname].stunnels }}'
      when: inventory_hostname in stunnel4vm_list

    - template:
        src: stunnel4_server.j2
        dest: /tmp/stunnel.conf
        mode: 0444
      vars:
        server:   '{{ stunnel4_servers_node[inventory_hostname] }}'
        clients:
          data:   '{{ stunnel4_clients_name }}'
          list:   '{{ stunnel4_clients }}'

- hosts: stunnel4_clients
  gather_facts: False
  tags: clients

  vars_files: *stunnel4

  tasks:

    - apt: name=stunnel4 state=present          
    - template:
        src: stunnel4_server.j2
        dest: /tmp/stunnel.conf
        mode: 0444
      vars:
        server:   False
        clients:
          data:   '{{ stunnel4_clients_name }}'
          list:   '{{ stunnel4vm_name[inventory_hostname].stunnels }}'
